- hosts: all
  become: yes
  remote_user: vagrant
  gather_facts: false
  vars_files:
    - config.yml
  tasks:
    - name: Apply git configuration
      community.general.git_config:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        scope: global
      become: no
      with_items: "{{ gitconfig }}"

    - name: Install python3
      apt:
        pkg:
        - python3
        - python3-pip
        - python-virtualenv
        update_cache: yes

    - name: Making virtualenv
      pip:
        requirements: /vagrant/django-base-backend/requirements.txt
        virtualenv: /home/vagrant/.venv
        virtualenv_python: python3
